@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":GuestCommandParser" as GuestCommandParser LOGIC_COLOR
participant ":GuestDeleteCommandParser" as GuestDeleteCommandParser LOGIC_COLOR
participant "d:GuestDeleteCommand" as GuestDeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("guest delete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("guest delete 1")
activate AddressBookParser

create GuestCommandParser
AddressBookParser -> GuestCommandParser
activate GuestCommandParser

GuestCommandParser --> AddressBookParser
deactivate GuestCommandParser

AddressBookParser -> GuestCommandParser : parse("delete 1")
activate GuestCommandParser

create GuestDeleteCommandParser
GuestCommandParser -> GuestDeleteCommandParser
activate GuestDeleteCommandParser

GuestDeleteCommandParser --> GuestCommandParser
deactivate GuestDeleteCommandParser

GuestCommandParser -> GuestDeleteCommandParser : parse("1")
activate GuestDeleteCommandParser

create GuestDeleteCommand
GuestDeleteCommandParser -> GuestDeleteCommand
activate GuestDeleteCommand

GuestDeleteCommand --> GuestDeleteCommandParser : d
deactivate GuestDeleteCommand

GuestDeleteCommandParser --> GuestCommandParser : d
deactivate GuestDeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GuestDeleteCommandParser -[hidden]-> GuestCommandParser
destroy GuestDeleteCommandParser

GuestCommandParser --> AddressBookParser : d
deactivate GuestCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GuestCommandParser -[hidden]-> AddressBookParser
destroy GuestCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> GuestDeleteCommand : execute()
activate GuestDeleteCommand

GuestDeleteCommand -> Model : deleteGuest(1)
activate Model

Model --> GuestDeleteCommand
deactivate Model

create CommandResult
GuestDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> GuestDeleteCommand
deactivate CommandResult

GuestDeleteCommand --> LogicManager : result
deactivate GuestDeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
