@startuml
!include style.puml


box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":VendorCommandParser" as VendorCommandParser LOGIC_COLOR
participant ":VendorFilterCommandParser" as VendorFilterCommandParser LOGIC_COLOR
participant ":VendorFilterCommand" as VendorFilterCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":XYZPredicate" as XYZPredicate MODEL_COLOR
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

note left LogicManager
input is "vendor filter n/John a/Jurong West St 65"
end note
[-> LogicManager: execute(input)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(input)
activate AddressBookParser

create VendorCommandParser
AddressBookParser -> VendorCommandParser
activate VendorCommandParser

create VendorFilterCommandParser
VendorCommandParser -> VendorFilterCommandParser
activate VendorFilterCommandParser
group ref [create list of predicates]
    VendorFilterCommandParser -[hidden]> XYZPredicate
end

create VendorFilterCommand
VendorFilterCommandParser -> VendorFilterCommand : VendorFilterCommand(predicates)
activate VendorFilterCommand

VendorFilterCommand --> VendorFilterCommandParser
deactivate VendorFilterCommand

VendorFilterCommandParser --> VendorCommandParser : f
deactivate VendorCommandParser

VendorCommandParser --> AddressBookParser : f
deactivate VendorCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> VendorFilterCommand : execute()
activate VendorFilterCommand

VendorFilterCommand -> ModelManager : updateFilteredVendorList(Predicate<? super Vendor>)
activate ModelManager

ModelManager --> VendorFilterCommand
deactivate ModelManager

create CommandResult
VendorFilterCommand -> CommandResult
activate CommandResult

CommandResult --> VendorFilterCommand
deactivate CommandResult

VendorFilterCommand --> LogicManager : r
deactivate VendorFilterCommand

[<-- LogicManager : r
deactivate LogicManager

@enduml
