@startuml
!include style.puml


participant ":VendorFilterCommandParser" as VendorFilterCommandParser LOGIC_COLOR

participant ":NamePredicate" as NamePredicate MODEL_COLOR
participant ":AddressPredicate" as AddressPredicate MODEL_COLOR
participant ":EmailPredicate" as EmailPredicate MODEL_COLOR
participant ":PhonePredicate" as PhonePredicate MODEL_COLOR

create VendorFilterCommandParser
group sd [create list of predicates]
    AddressPredicate -[hidden]-> VendorFilterCommandParser

    group opt [input contains Name prefix]
        create NamePredicate
        activate VendorFilterCommandParser
        VendorFilterCommandParser -> NamePredicate
        activate NamePredicate
        NamePredicate -> VendorFilterCommandParser
        deactivate NamePredicate
    end

    group opt [input contains Address prefix]
        create AddressPredicate
        VendorFilterCommandParser -> AddressPredicate
        activate AddressPredicate
        AddressPredicate -> VendorFilterCommandParser
        deactivate AddressPredicate
    end

    group opt [input contains Email prefix]
            create EmailPredicate
            VendorFilterCommandParser -> EmailPredicate
            activate EmailPredicate
            EmailPredicate -> VendorFilterCommandParser
            deactivate EmailPredicate
    end

    group opt [input contains Phone prefix]
            create PhonePredicate
            VendorFilterCommandParser -> PhonePredicate
            activate PhonePredicate
            PhonePredicate -> VendorFilterCommandParser
            deactivate PhonePredicate
    end
end
@enduml
