@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class "<<interface>>\nPredicate" as Predicate #444444

note left
Predicate<Person>
end note

NamePredicate .up.|> Predicate
AddressPredicate .up.|> Predicate
EmailPredicate .up.|> Predicate
PhonePredicate .up.|> Predicate

@enduml
